target 'MantisExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for MantisExample
  pod 'Mantis', :path => '../'

  target 'MantisExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
