# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MantisExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MantisExample
  pod 'Mantis', :path => '../'
#  pod 'Mantis', '~> 1.1.0'

  target 'MantisExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
